### PR TITLE
Add links in installed-tools

### LINKED ISSUE #21: Add relevant links to projects on "Installed Tools"
Many tools in the project list have a project website. Please find and add links to the projects itself. If you don't find any link check the Ubuntu documentation (https://help.ubuntu.com/community/Lubuntu/Setup#Installed_Tools) and Wikipedia documentation.

### PR DESCRIPTION
**Pull request by ms10398**
Fixes #21 

Please review @mariobehling

### CODE REVIEW

**Comment by ms10398** [comment]
By actual project homepage you mean like this-
https://apps.ubuntu.com/cat/applications/precise/hardinfo/
As almost all of them dont have thier own webpage

**Comment by mariobehling** [comment]
Please check every component, 
* e.g. Wikipedia gives this site for Synaptic: http://www.nongnu.org/synaptic/
* https://wiki.lxde.org/en/LXTask
* http://ndiswrapper.sourceforge.net
* https://www.jwz.org/xscreensaver/

Wikipedia and Google are your friends. Find the project site wherever possible.

**Comment by ms10398** [comment]
Please check now @mariobehling

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
