### PR TITLE
Add docs for Lubuntu 16.04

### PR DESCRIPTION
**Pull request by 0x48piraj**
## Changes  : 

* Created `lubuntu1604_downloads.md` 
* Added docs to `lubuntu1604_downloads.md`

> Reference : http://cdimage.ubuntu.com/lubuntu/releases/16.04/release/

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Ping @mariobehling @ParthS007 :+1:

**Comment by mariobehling** [comment]
Hi, the release notes of 16.04 are still not working as epxected. Please check and open and issue and help to fix it: https://docs.lubuntu.net/releases/lubuntu1604_release_notes.html

**Comment by ms10398** [comment]
Will work on this

**Comment by 0x48piraj** [comment]
Which parts @ms10398 ?
Is it the formatting that's causing problems ?

**Pull request merged**
