### PR TITLE
Added 11.10 release notes

### PR DESCRIPTION
**Pull request by Logan1x**

### CODE REVIEW

**Comment by Logan1x** [comment]
@ParthS007 not able to find download info can you provide the link?

**Comment by Logan1x** [comment]
https://wiki.ubuntu.com/Lubuntu/Announcement/11.10 no source to for download information.

**Comment by ParthS007** [comment]
@Logan1x  that's the main work you have to do, you have to find it.

**Comment by Logan1x** [comment]
I've tried most of the blog post and all are forwarding to http://cdimage.ubuntu.com/lubuntu/releases/11.10/release this page

**Comment by mariobehling** [comment]
Ok, just add the info as is and we need to find a way to put up the image elsewhere later.

**Comment by mariobehling** [comment]
Added an issue here: https://github.com/lubuntu-dev/docs.lubuntu.net/issues/48

**Comment by Logan1x** [comment]
yes, @mariobehling  because if we post the download link from unofficial page then we can not guarantee that the image is not manipulated.

**Comment by mariobehling** [comment]
There are university sites and magazins, which should be ok and trustworthy.

**Pull request merged**
