### PR TITLE
Added social media icons.

### PR DESCRIPTION
**Pull request by alirizwi**
Added icons for social media  at the end of the link section and above the Licence.

Fixes: https://github.com/lubuntu-dev/docs.lubuntu.net/issues/11

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve conflicts and put icons into a folder `/img` instead of adding external images.

**Comment by mariobehling** [comment]
Please provide the link to your preview page on your github repo.

**Comment by mariobehling** [comment]
Also ensure icons are all in the same size, please.

**Comment by alirizwi** [comment]
Preview of the icons:

icons

**Comment by mariobehling** [comment]
Thanks. Please see my earlier comments. These things should be relatively easy to solve. Keep it up :-)

**Comment by alirizwi** [comment]
@mariobehling i have the changes. Please review. Thanks

**Comment by mariobehling** [comment]
Please provide the icons all in the same size and in one color.

**Comment by alirizwi** [comment]
@mariobehling Please review.
lbuntu

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
